USE v_parrot;

CREATE TABLE `equipements` (
  `id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `categorie` varchar(255) NOT NULL,
  `description` varchar(255) NOT NULL
) ENGINE = InnoDB CHARSET=utf8mb4 COLLATE utf8mb4_general_ci;

INSERT INTO `equipements` (`id`, `categorie`, `description`) VALUES
(NULL, 'Confort', 'Climatisation'),
(NULL, 'Confort', 'Vitres electrique'),
(NULL, 'Confort', 'Ajustement des miroirs latéraux'),
(NULL, 'Confort', 'Miroirs arrière pliants électriques'),
(NULL, 'Confort', 'Frein de stationnement électrique'),
(NULL, 'Confort', 'Disque mécanismes de freinage roues arrières'),
(NULL, 'Confort', 'Régulateur de vitesse'),
(NULL, 'Confort', 'Essuie-glaces avec capteur de pluie'),
(NULL, 'Confort', 'Protection thermique vitrage'),
(NULL, 'Confort', 'Verres arrière tonifiantes'),
(NULL, 'Confort', "Tronc de couvercle d'entraînement électrique"),
(NULL, 'Confort', 'Notes de porte'),
(NULL, 'Confort', "Système d'accès incinuel et bouton de démarrage du moteur"),
(NULL, 'Confort', 'Système multimédia / audio / navigation'),
(NULL, 'Confort', 'Volant multifonctionnel'),
(NULL, 'Confort', 'Volant sport gainé cuir'),
(NULL, 'Confort', 'Terrain de volant en cuir et poignée de sélecteur de stylo'),
(NULL, 'Confort', 'Réglage de la colonne de direction sur vol et inclinaison'),
(NULL, 'Confort', 'Ajustement électrique des sièges avant'),
(NULL, 'Confort', 'Mémoire du siège du conducteur et miroirs'),
(NULL, 'Confort', 'Toit avec vue panoramique'),
(NULL, 'Confort', 'Toit ouvrant avec vue panoramique'),
(NULL, 'Confort', 'Ventilation des sièges avant'),
(NULL, 'Confort', 'Accoudoir central avant'),
(NULL, 'Confort', 'Accoudoir central pour sièges arrière'),
(NULL, 'Confort', 'GPS'),
(NULL, 'Confort', 'Sellerie cuir'),
(NULL, 'Confort', 'Sellerie mixte cuir/tissu'),
(NULL, 'Confort', 'Prise USB'),
(NULL, 'Confort', 'Système Bluetooth'),
(NULL, 'Confort', 'Sound système amplifié'),
(NULL, 'Confort', 'Apple Car Play'),
(NULL, 'Confort', 'Android Auto'),
(NULL, 'Confort', 'Hayon de coffre assisté électriquement'),
(NULL, 'Halte de protection', 'Verrouillage central avec télécommande'),
(NULL, 'Halte de protection', 'Signalisation'),
(NULL, 'Halte de protection', 'Immobilisation électronique'),
(NULL, 'Lumières', 'Phare Dynamique Xenon / LED avec laveuse'),
(NULL, 'Lumières', 'Projecteurs antibrouillard avant à LED'),
(NULL, 'Lumières', "Phare à LED"),
(NULL, 'Lumières', 'Inclusion automatique de la toison'),
(NULL, 'Lumières', 'Commutation automatique des phares lointains / trempés'),
(NULL, "Options d'hiver", 'Pare-brise chauffé'),
(NULL, "Options d'hiver", 'Miroirs latéraux de chauffage'),
(NULL, "Options d'hiver", 'Chauffage des injecteurs de lunettes'),
(NULL, "Options d'hiver", 'Chauffage des sièges avant et arrière'),
(NULL, "Options d'hiver", 'Volant chauffé'),
(NULL, 'Assistance au stationnement', 'Caméra de vision arrière'),
(NULL, 'Assistance au stationnement', 'Radar de recul arrière'),
(NULL, 'Assistance au stationnement', 'Radar de stationnement avant'),
(NULL, 'Assistance au stationnement', 'Système de stationnement automatique'),
(NULL, 'Sécurité', 'ABS (anti-verrouillage)'),
(NULL, 'Sécurité', 'ESP (Système de stabilité en monnaie électronique)'),
(NULL, 'Sécurité', 'Système de freinage automatique'),
(NULL, 'Sécurité', "Système d'aide lors de la montée"),
(NULL, 'Sécurité', "Système de contrôle de pression des pneus"),
(NULL, 'Sécurité', "Fixation des sièges pour enfants ISOFIX"),
(NULL, 'Sécurité', "Airbags"),
(NULL, 'Esthétique', "Jantes Alliage"),
(NULL, 'Esthétique', "Peinture métallisée");